# Generated by Django 3.2 on 2023-02-07 17:57

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230206_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), reviews.validators.max_year_title], verbose_name='Год выпуска'),
        ),
    ]
